INSERT INTO orders(description, cost, revenue, order_time)
VALUES('Construction Materials', 100.00, 4200.00, CURRENT_TIMESTAMP)
INSERT INTO orders(description, cost, revenue, order_time)
VALUES('Construction Materials', 71.38, 3948.45, CURRENT_TIMESTAMP)
INSERT INTO orders(description, cost, revenue, order_time)
VALUES('Wood and Lumber', 263.88, 1950.52, CURRENT_TIMESTAMP)
INSERT INTO orders(description, cost, revenue, order_time)
VALUES('Wood and Lumber', 116.98, 4991.45, CURRENT_TIMESTAMP)
INSERT INTO orders(description, cost, revenue, order_time)
VALUES('Meat', 279.17, 6739.72, CURRENT_TIMESTAMP)
INSERT INTO orders(description, cost, revenue, order_time)
VALUES('Meat', 537.91, 3618.08, CURRENT_TIMESTAMP)
INSERT INTO orders(description, cost, revenue, order_time)
VALUES('Fresh Produce', 420.69, 5345.91, CURRENT_TIMESTAMP)
INSERT INTO orders(description, cost, revenue, order_time)
VALUES('Farm Supplies', 171.13, 47429.78, CURRENT_TIMESTAMP)
INSERT INTO orders(description, cost, revenue, order_time)
VALUES('Cheetos', 310.98, 7231.98, CURRENT_TIMESTAMP)
INSERT INTO orders(description, cost, revenue, order_time)
VALUES('Rose Rocket Swag Shirts', 350.79, 5404.24, CURRENT_TIMESTAMP)